application: omnimobi
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/fonts
  static_dir: static/fonts

- url: /static/css
  static_dir: static/css

- url: /static/img
  static_dir: static/img

- url: /static/js
  static_dir: static/js

- url: /.*
  script: omni.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest